name: Publish Kubo Package
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: ['main']

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish:
    name: Build & Publish package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      #- name: Exit if not on release branch
      #  if: endsWith(github.ref, 'release') == false
      #  run: exit -1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get previous version from Git history
        id: get_previous_version
        run: |
          pwd
          git fetch --tags
          PREVIOUS_VERSION=$(git describe --tags --abbrev=0)
          echo "::set-output name=previous_version::$PREVIOUS_VERSION"
          echo $PREVIOUS_VERSION

      - name: Check if package.json version is newer
        run: |
          CURRENT_VERSION=$(node -p "require('./packages/kubo/package.json').version")
          PREVIOUS_VERSION=${{ steps.get_previous_version.outputs.previous_version }}
          echo "::set-output name=current_version::$CURRENT_VERSION"

          if [ "$(printf '%s\n' "$CURRENT_VERSION" "$PREVIOUS_VERSION" | sort -V | head -n 1)" != "$CURRENT_VERSION" ]; then
            echo "Error: Package.json version is not newer than the previous version."
            exit 1
          else
            echo "Package.json version is newer than the previous version."
          fi

      - name: Install dependencies
        run: npm i

      - name: Publish package to NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
          npm run release
          git tag $CURRENT_VERSION
          git push origin --tags
